export const topics = [
  "HTML",
  "CSS",
  "Javascript",
  "React",
  "ThreeJS",
  "NextJS",
  "MongoDB",
  "Server",
  "AWS",
  "Blender",
  "Effect",
  "Improve",
  "Performance",
  "Security",
  "Error",
  "QnA",
];

export const topicColor = {
  html: "#dde1e6",
  css: "#dddde6",
  javascript: "#e1dde6",
  react: "#e1e6dd",
  threejs: "#dde6df",
  nextjs: "#abafb3",
  mongodb: "#dde6df",
  server: "#d7d6b8",
  aws: "#e6e5dd",
  blender: "#e6e0dd",
  effect: "#dde6e4",
  improve: "#e2dde6",
  performance: "#a3c7d7",
  security: "#e6e0dd",
  error: "#e6dddd",
};
